### ISSUE TITLE
Sugestion to remove the Moment.js 

### ISSUE THREAD

**Issue by Soldy** [Save-the-code/Github-Contribution-Hack#1]
I think you don't need it. You can use the unixtimestamp that's always UTC.

**Comment by SatYu26** [comment]
Yeah i guess that would also serve the purpose. 
Will use it and make commit or if you are free you can also add it.

> I think you don't need it. You can use the unixtimestamp that's always UTC.

**Comment by Soldy** [comment]
Yes because the temporal. 
https://tc39.es/proposal-temporal/docs/index.html
That should be comming soon.
